name: 'SDM Create Service Account GH Action'
description: 'Create a SDM Service Account'
inputs:
  account-id:
    description: SDM Account ID
    required: true
  run-id:
    description: 'Github Action Workflow run id'
    required: true
  random-key-job-name:
    description: 'Workflow Job name responsible for printing the random UUID (v4) key in the format "###random_access_key=RANDOM_UUID_KEY###"'
    required: true
  random-key:
    description: 'Random Access Key'
    required: true
  secret:
    description: 'Shared Secret'
    required: true
  server-host:
    description: 'Proxy host address'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SDM_ACCOUNT_ID: ${{ inputs.account-id }}
    RUN_ID: ${{ inputs.run-id }}
    RANDOM_KEY_JOB_NAME: ${{ inputs.random-key-job-name }}
    RANDOM_KEY: ${{ inputs.random-key }}
    SECRET: ${{ inputs.secret }}
    SERVER_HOST: ${{ inputs.server-host }}
